-- Module de scan unifié (Lot 1)
-- 1) Traçabilité enrichie des mouvements de zone.
ALTER TABLE "ZoneMovement" ADD COLUMN IF NOT EXISTS "autoGenerated" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "ZoneMovement" ADD COLUMN IF NOT EXISTS "reason" TEXT;
ALTER TABLE "ZoneMovement" ADD COLUMN IF NOT EXISTS "batchId" TEXT;
ALTER TABLE "ZoneMovement" ADD COLUMN IF NOT EXISTS "scanType" TEXT;
ALTER TABLE "ZoneMovement" ADD COLUMN IF NOT EXISTS "scannedValue" TEXT;

CREATE INDEX IF NOT EXISTS "ZoneMovement_batchId_idx" ON "ZoneMovement"("batchId");

-- 2) Colonnes normalisées de plaque pour une recherche indexée et fiable.
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "plateNormalized" TEXT;
ALTER TABLE "Vehicle" ADD COLUMN IF NOT EXISTS "trailerPlateNormalized" TEXT;

-- Backfill : normalisation = uppercase + suppression de tout caractère non
-- alphanumérique. NULL si la valeur normalisée est vide.
UPDATE "Vehicle"
SET "plateNormalized" = NULLIF(UPPER(REGEXP_REPLACE("plate", '[^a-zA-Z0-9]', '', 'g')), '')
WHERE "plate" IS NOT NULL;

UPDATE "Vehicle"
SET "trailerPlateNormalized" = NULLIF(UPPER(REGEXP_REPLACE("trailerPlate", '[^a-zA-Z0-9]', '', 'g')), '')
WHERE "trailerPlate" IS NOT NULL;

CREATE INDEX IF NOT EXISTS "Vehicle_plateNormalized_idx" ON "Vehicle"("plateNormalized");
CREATE INDEX IF NOT EXISTS "Vehicle_trailerPlateNormalized_idx" ON "Vehicle"("trailerPlateNormalized");
