import type { Metadata, Viewport } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
  userScalable: false,
};

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr">
      <body
        className={`
          ${geistSans.variable}
          ${geistMono.variable}
          ${inter.variable}
          font-sans
          antialiased
          bg-[#F9FAFD]
        `}
      >
        {children}
        {/* TODO(démo): retirer ce lien après la présentation Yachting 2026 */}
        <a
          href="/demo/yachting-2026-accreditations-logistiques.html"
          className="fixed bottom-[calc(1rem+env(safe-area-inset-bottom,0px))] right-4 z-[9999] rounded-full bg-slate-900 px-3 py-2 text-xs font-medium text-white shadow-lg ring-1 ring-white/10 transition hover:bg-slate-800 sm:bottom-6 sm:right-6 sm:px-4 sm:text-sm"
        >
          Démo maquette Yachting
        </a>
      </body>
    </html>
  );
}
